### PR TITLE
Release 1.2.1b1

### PR DESCRIPTION
**Pull request by huri000**
Included content will be released as beta soon.
## Includes
- support `.darkContent` status bar on iOS 13.
- patch that allows `SwiftEntryKit` to be compatible with `SwiftUI`.

### CODE REVIEW

**Comment by huri000** [comment]
pending confirmation of #211's issuer.

**Comment by aidev1065** [comment]
Hopefully this release will include the fix for SwiftEntryKit not displaying anything for apps using the new UIScene API for iOS 13 in the SceneConfiguration

**Comment by chrishannah** [comment]
I was having this exact issue after I started to use the new UIScene stuff, and I can confirm that this fixed it for me!

**Comment by huri000** [comment]
@aidev1065 , @chrishannah this fix is available on `1.2.0` 💎

**Comment by MrDazt** [comment]
Xcode 10.3 brings error for tests on line .darkContent not found
I guess need to add check for #if compiler(>=5.1)

**Pull request merged**
