### PR TITLE
Enable/Disable rotation flag

### PR DESCRIPTION
**Pull request by maeji**
Exist app if don't went rotation enable, it should can be enable/disable rotation control.

### Issue Link 🔗
*A link to the issue & short explanation*

### Goals 🥅
*What have I tried to achieve / improve + use case example*

### Implementation Details ✏️
- Add rotation Enable/Disable property in EKAttributes.
- Add rotation control in EKRootViewController.

### Testing Details 🔍
*How did I test my implementation*

### Screenshot Links 📷
*Since this a visual project, focusing maily on UI and UX, please attach screenshots in case of UI related change*

### CODE REVIEW

**Comment by huri000** [comment]
Thanks! Will be reviewed in the next few days.

**Comment by huri000** [comment]
@maeji - Thanks. I've reviewed your code and I have few observations:
0. Resolve the conflicts.
1. Please rename `enableRotate` to `isRotationEnabled` which is more readable and convensional.
2. Move `isRatationEnabled` into PositionConstraints (It is the construct that decided the constraints that applies to the position of the entry).
3. I trust you tested your implementation using the example project, yes? 
Thanks!

**Comment by maeji** [comment]
@huri000 I changed flag name and move to PositionConstraints. Sure I'm tested that :-) It shipped in my product. :-) Thank you!

**Comment by huri000** [comment]
Thanks! I'll review it during the weekend!

**Comment by huri000** [comment]
Great, thanks @maeji!

**Pull request merged**
