### PR TITLE
Additional EKProperty init method to support [ButtonContent] parameter

### PR DESCRIPTION
**Pull request by NiallKiddle**
*Issue Link* 🔗
https://github.com/huri000/SwiftEntryKit/issues/187

*Details* ✏️
ButtonBarContent can now be initialised using an array of ButtonContent as well as the original variadic. This is useful when creating a controller class and passing in multiple buttons when creating the alert.

### CODE REVIEW

**Comment by NiallKiddle** [comment]
Hey @huri000 please could you review this pull request if possible, thanks.

**Comment by huri000** [comment]
Thanks!

**Comment by huri000** [comment]
`1.0.2` will be released in the next few days.

**Comment by swarajsinghdev** [comment]
> `1.0.2` will be released in the next few days.

i haven't seen any multiple button support

**Pull request merged**
